Adds turborepo optional deps (#13)
When trying to setup this repo, upon running `npm install`, I was seeing
the following error:
```
npm ERR! code 1
npm ERR! path /Users/laura/Development/playground/easy-ui/node_modules/turbo
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! [turbo] Failed to find package "turbo-darwin-64" on the file system
npm ERR!
npm ERR! This can happen if you use the "--no-optional" flag. The "optionalDependencies"
npm ERR! package.json feature is used by turbo to install the correct binary executable
npm ERR! for your current platform. This install script will now attempt to work around
npm ERR! this. If that fails, you need to remove the "--no-optional" flag to use turbo.
npm ERR!
npm ERR! node:internal/modules/cjs/loader:933
npm ERR!   const err = new Error(message);
npm ERR!               ^
npm ERR!
npm ERR! Error: Cannot find module 'turbo'
npm ERR! Require stack:
npm ERR! - /Users/laura/Development/playground/easy-ui/node_modules/turbo/node-platform.js
npm ERR! - /Users/laura/Development/playground/easy-ui/node_modules/turbo/install.js
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
npm ERR!     at downloadedBinPath (/Users/laura/Development/playground/easy-ui/node_modules/turbo/node-platform.js:44:44)
npm ERR!     at checkAndPreparePackage (/Users/laura/Development/playground/easy-ui/node_modules/turbo/install.js:285:15)
npm ERR!     at Object.<anonymous> (/Users/laura/Development/playground/easy-ui/node_modules/turbo/install.js:310:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/laura/Development/playground/easy-ui/node_modules/turbo/node-platform.js',
npm ERR!     '/Users/laura/Development/playground/easy-ui/node_modules/turbo/install.js'
npm ERR!   ]
npm ERR! }
```
I ran `npm install -D --arch=arm64 --platform=darwin turbo@1.7.3` to
install the architecture and now `npm install` runs successfully.